// <auto-generated />
namespace Incubators.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_eggs_to_incubators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_eggs_to_incubators));
        
        string IMigrationMetadata.Id
        {
            get { return "201701151833064_added_eggs_to_incubators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
